// This file contains styles for the Blinkit-like frontend
export const styles = {
  app: {
    fontFamily: 'Poppins, Arial, sans-serif',
    background: '#f8f8f8',
    minHeight: '100vh',
    color: '#222',
    letterSpacing: '0.01em',
  },
  header: {
    background: '#fff',
    padding: '0 32px',
    boxShadow: '0 2px 8px #e0e0e0',
    display: 'flex',
    alignItems: 'center',
    height: 72,
    justifyContent: 'flex-start',
    gap: 32,
    borderBottom: '1px solid #f0f0f0',
  },
  logo: {
    fontWeight: 700,
    fontSize: 32,
    color: '#6cc24a',
    marginRight: 32,
    letterSpacing: '-2px',
    fontFamily: 'Poppins, Arial, sans-serif',
  },
  location: {
    fontWeight: 500,
    fontSize: 18,
    color: '#222',
    marginRight: 32,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  searchWrap: {
    position: 'relative',
    flex: 1,
    maxWidth: 420,
    marginRight: 32,
    display: 'flex',
    alignItems: 'center',
  },
  searchInput: {
    padding: '10px 44px 10px 18px',
    borderRadius: 8,
    border: '1.5px solid #d1d5db',
    fontSize: 18,
    width: '100%',
    background: '#f5f5f5',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border 0.2s',
  },
  searchIcon: {
    position: 'absolute',
    right: 18,
    top: '50%',
    transform: 'translateY(-50%)',
    width: 24,
    height: 24,
    pointerEvents: 'none',
    opacity: 0.7,
  },
  cartBtn: {
    background: '#fff',
    border: '1.5px solid #6cc24a',
    color: '#222',
    borderRadius: 8,
    padding: '10px 28px',
    fontWeight: 600,
    fontSize: 18,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    boxShadow: '0 2px 8px #eee',
  },
  main: {
    padding: '32px 0',
    maxWidth: 1200,
    margin: '0 auto',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 24,
    color: '#222',
    fontFamily: 'Poppins, Arial, sans-serif',
  },
  productGrid: {
    display: 'flex',
    gap: 24,
    flexWrap: 'wrap',
  },
  productCard: {
    background: '#fff',
    borderRadius: 16,
    boxShadow: '0 2px 8px #eee',
    width: 240,
    padding: 18,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    transition: 'box-shadow 0.2s',
  },
  productImg: {
    width: 180,
    height: 120,
    objectFit: 'cover',
    borderRadius: 10,
    marginBottom: 10,
  },
  productName: {
    marginTop: 8,
    fontWeight: 600,
    fontSize: 16,
    textAlign: 'center',
    minHeight: 44,
    fontFamily: 'Poppins, Arial, sans-serif',
  },
  productVolume: {
    color: '#888',
    fontSize: 14,
    marginBottom: 4,
  },
  priceRow: {
    margin: '8px 0',
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  price: {
    fontWeight: 700,
    color: '#222',
  },
  originalPrice: {
    textDecoration: 'line-through',
    color: '#aaa',
    fontSize: 15,
  },
  discount: {
    color: '#6cc24a',
    fontWeight: 600,
    fontSize: 15,
  },
  delivery: {
    color: '#6cc24a',
    fontSize: 13,
    marginBottom: 6,
  },
  addBtn: {
    marginTop: 10,
    background: 'linear-gradient(90deg, #6cc24a 60%, #4bb543 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 32px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 16,
    transition: 'background 0.2s',
    boxShadow: '0 2px 8px #e0e0e0',
    fontFamily: 'Poppins, Arial, sans-serif',
  },
};
